openapi: "3.0.0"
info:
  title: Service API
  version: "1.0"
paths:
  /api/invoices:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  price: {type: string}
                  is_verified: {type: string}
                  deleted_at: {type: string}
