openapi: "3.0.0"
info:
  title: Service API
  version: "1.0"
paths:
  /api/reports:
    get:
      summary: Get
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer_id: {type: string}
