openapi: "3.0.0"
info:
  title: Users API
  version: "2.0"
paths:
  /v2/members/{id}:
    delete:
      summary: Delete member
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted
