openapi: "3.0.0"
info:
  title: Service API
  version: "1.0"
paths:
  /api/contracts:
    get:
      summary: Get
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: {type: string}
                  metadata: {type: string}
