openapi: "3.0.0"
info:
  title: Service API
  version: "1.0"
paths:
  /api/webhooks:
    get:
      summary: Endpoint
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  name: {type: string}
                  created_at: {type: string}
