openapi: "3.0.0"
info:
  title: Service API
  version: "v2"
paths:
  /v2/devices:
    get:
      summary: Endpoint
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  price: {type: string}
                  id: {type: string}
