openapi: "3.0.0"
info:
  title: Service API
  version: "v1"
paths:
  /v1/warehouses:
    get:
      summary: Endpoint
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  country: {type: string}
                  id: {type: string}
