openapi: "3.0.0"
info:
  title: Service API
  version: "1.0"
paths:
  /api/transactions:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  fee: {type: string}
                  tier: {type: string}
                  state: {type: string}
