openapi: "3.0.0"
info: {title: API, version: "1.0"}
paths:
  /api/transactions:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: {type: string}
                  name: {type: string}
                  description: {type: string}
